CREATE TABLE JADWAL_NON_SIDANG
(
    IdJadwal INTEGER PRIMARY KEY NOT NULL,
    Tanggalmulai DATE NOT NULL,
    Tanggalselesai DATE NOT NULL,
    Alasan VARCHAR(100) NOT NULL,
    Repitisi VARCHAR(50),
    NIPdosen VARCHAR(10) NOT NULL REFERENCES DOSEN(NIP)
);

CREATE TABLE PRODI
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NamaProdi VARCHAR(50) NOT NULL
);

CREATE TABLE TIMELINE
(
    IdTimeline INTEGER PRIMARY KEY NOT NULL,
    NamaEvent VARCHAR(100) NOT NULL,
    Tanggal DATE NOT NULL,
    Tahun INTEGER NOT NULL,
    Semester INTEGER NOT NULL,
    FOREIGN KEY (tahun, semester) REFERENCES sisidang.term (tahun, semester)
);